implemented guard let, JSONDecoder, code keys, combined 2 fetching funcs
mattmaloof/DeBlockWallet pull request #2
Opened 2023-09-19 19:45 UTC by k-code00

fetched eth price (crypto) and printed it in usd, eur, gbp (currency)

2023-09-19 19:52 UTC, mattmaloof requested changes

2023-09-19 19:52 UTC, mattmaloof commented on DeBlockWallet/Model.swift
> +//struct Crypto: Decodable {
Should not have so much commented code.

2023-09-19 19:52 UTC, mattmaloof commented on DeBlockWallet/NetworkManager.swift
> +    //let gasPrice = "https://api.etherscan.io/api?module=gastracker&action=gasoracle&apikey=\(apiKey)"
Extra commented code here.

2023-09-19 19:52 UTC, mattmaloof commented on DeBlockWallet/NetworkManager.swift
> +                print("Failed to decode JSON:", error.localizedDescription)
Use closure, need to return an error and need to use completion handler to communicate the data between classes.

2023-09-19 19:52 UTC, mattmaloof commented on DeBlockWallet/NetworkManager.swift
> +            } catch {
Return error, use completion handler / closure to communicate code between classes.

2023-09-20 00:34 UTC, ChopperTheKing reviewed
Looks good so far.

2023-09-20 00:34 UTC, mattmaloof approved these changes

2023-09-20 00:38 UTC, merged